version: '3.2'

services:

    api:
        build: .
        ports:
            - 8000:8000
        depends_on:
            - db
            - cache
        restart: unless-stopped
        env_file: .env
        environment:
            DB_HOST: db
        volumes:
            - ./volume_uwsgispooler:/var/uwsgispooler
            - ./volume_uwsgilog:/var/log/uwsgi/

    db:
        build: ../postgres
        #image: cualbondi/postgres
        restart: unless-stopped
        volumes:
            - ./volume_db:/var/lib/postgresql/data
        env_file: .env

    cache:
        image: memcached:alpine
        restart: unless-stopped